sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t emaynewrelic/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true emaynewrelic/docker-react npm run test